# 🗄️ DATABASE (Supabase / PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.jyasaywtvlzybdhcjmgz
spring.datasource.password=16671667

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ☁️ SUPABASE STORAGE CONFIG
supabase.url=https://jyasaywtvlzybdhcjmgz.supabase.co
supabase.bucket=Uploads
supabase.apiKey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5YXNheXd0dmx6eWJkaGNqbWd6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mjc0MTE4MywiZXhwIjoyMDc4MzE3MTgzfQ.gzfZbx249ayWwazQ3K-hVFhgfKTfrg0OngyTuYw2F-c

# 🔐 JWT Secret
jwt.secret=KZGRhiocq33Hc7S9U0Qztu07sZtp6QZu0M8+EUs8XUgkuq+tlqCwNEvOhzJblrj/6izFJJj157ckvuS8Z0r6iQ==
jwt.expiration=86400000